
spring:
  datasource:
    password:
    username: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:C:/h2data/sample
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  

  h2:
    console:
      enabled: true
  application:
    name: tourist-guide-service
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"      

       