server:
  port: 9494

spring:
  application:
    name: admin-server  
  boot:
    admin:
      discovery:
        converter:
          management-context-path: /api/v1/actuator
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/