spring:
  application:
    name: eureka-default
  
  
server:
  port: 5050
  
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-peer2:8561/eureka,
                            http://eureka-peer1:8461/eureka

